
export const GET_PRICE_DATA_START = 'GET_PRICE_DATA_START';
export const GET_PRICE_DATA_FAILED = 'GET_PRICE_DATA_FAILED';
export const GET_PRICE_DATA_SUCCED = 'GET_PRICE_DATA_SUCCED';

export const NEWS_DATA_START = 'NEWS_DATA_START';
export const NEWS_DATA_FAILED = 'NEWS_DATA_FAILED';
export const NEWS_DATA_SUCCED = 'NEWS_DATA_SUCCED';